group_tinder/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from web import views

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url('^', include('django.contrib.auth.urls')),
    url(r'^home/', views.home, name='home'),
    url(r'^accounts/', include('registration.backends.simple.urls')),
    url(r'^accounts/profile/', views.profile, name='profile'),
    url(r'^people/', views.people, name='people'),
    url(r'^groups/', views.groups, name='groups'),
]

web/models.py
from django.db import models
from django.db.models import Count
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.auth.models import User
from random import randint, getrandbits, choice


class PersonsManager(models.Manager):
    def random(self):
        count = self.aggregate(count=Count('pk'))['count']
        random_index = randint(0, count - 1)
        return self.all()[random_index]

    def create_random(self, user):
        gender = Person.GENDERS[0][0] if bool(getrandbits(1)) else Person.GENDERS[1][0]
        stereotype = choice(Person.STEREOTYPES)[0]
        return Person(user=user, age=randint(13, 65), gender=gender, stereotype=stereotype)


class Person(models.Model):
    objects = PersonsManager()
    GENDERS = (
        ('m', 'Male'),
        ('f', 'Female'),
    )
    STEREOTYPES = (
        (0, 'Jock'),
        (1, 'Hippie'),
        (2, 'Bro'),
        (3, 'Diva'),
        (4, 'Bookworm'),
        (5, 'Techie'),
        (6, 'Dancer'),
        (7, 'Emo'),
    )
    user = models.OneToOneField(User, primary_key=True)
    age = models.IntegerField()
    gender = models.CharField(max_length=1, choices=GENDERS)
    stereotype = models.IntegerField(choices=STEREOTYPES)

    def __str__(self):
        return 'Person[pk=%s,age=%s,gender=%s,stereotype=%s]' % (self.pk, self.age, self.gender, self.stereotype)


class Judgement(models.Model):
    class Meta:
        unique_together = (("judge", "judged"),)
    judge = models.ForeignKey(Person, verbose_name='the person judging', related_name='%(app_label)s_%(class)s_made')
    judged = models.ForeignKey(Person, verbose_name='the person being judged', related_name='%(app_label)s_%(class)s_received')
    ruling = models.BooleanField('the value of the judgement')


class MatchesManager(models.Manager):
    def get_existing(self, a, b):
        match = None
        try:
            match = self.get(initiated=a, agreed=b)
            return match
        except ObjectDoesNotExist:
            pass
        try:
            match = self.get(agreed=a, initiated=b)
        except ObjectDoesNotExist:
            pass
        return match


class Match(models.Model):
    objects = MatchesManager()

    class Meta:
        unique_together = (("initiated", "agreed"),)

    initiated = models.ForeignKey(Person, verbose_name='Initiator of match', related_name='%(app_label)s_%(class)s_initiated')
    agreed = models.ForeignKey(Person, verbose_name='Matched in agreement', related_name='%(app_label)s_%(class)s_agreed')


class GroupsManager(models.Manager):
    def create(self, a, b, c):
        init_hash = self.get_hash(a, b, c)
        group = Group(init_hash=init_hash)
        group.save()
        group.people.add(a, b, c)
        return group

    def get_existing(self, a, b, c):
        init_hash = self.get_hash(a, b, c)
        try:
            existing = self.get(init_hash=init_hash)
            return existing
        except ObjectDoesNotExist:
            pass
        return None

    def get_hash(self, a, b, c):
        pks = sorted([a.pk, b.pk, c.pk])
        return hash('%s:%s:%s' % (pks[0], pks[1], pks[2]))


class Group(models.Model):
    objects = GroupsManager()

    init_hash = models.IntegerField(unique=True)
    people = models.ManyToManyField(Person)

    def __str__(self):
        return 'Group[init_hash=%s]' % (self.init_hash)

web/forms.py
from django import forms
from models import Person

class PersonForm(forms.ModelForm):
    class Meta:
        model = Person
        fields = ['age', 'gender', 'stereotype']

web/views.py
from django.shortcuts import render_to_response, redirect
from django.http import HttpResponse
from django.core.exceptions import ObjectDoesNotExist
from django.template import RequestContext
from models import Person, User, Judgement
from .forms import PersonForm
from services import group_service, fake_service, person_service
from django.db import IntegrityError

def home(request):
    user = request.user
    return render_to_response('home.html', {'user': user})

def profile(request):
    if not request.user.is_active:
        return redirect('/accounts/login')
    user = request.user
    try:
        person = Person.objects.get(user=user)
    except ObjectDoesNotExist:
        person = None

    if request.method == 'POST':
        form = PersonForm(request.POST)
        # check whether it's valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required
            person = form.save(commit=False)
            person.user = user
            person.save()
            # redirect to a new URL:
            return redirect('/accounts/profile/')
    # if a GET (or any other method) we'll create a blank form
    elif person is None:
        form = PersonForm()
    elif request.GET.get('edit'):
        form = PersonForm(instance=person)
    else:
        form = None

    return render_to_response('profile.html', {'user': user, 'person': person, 'form': form}, context_instance=RequestContext(request))

def people(request):
    if not request.user.is_active:
        return redirect('/accounts/login')
    user = request.user
    person = user.person
    if person is None:
        return redirect('/accounts/profile/?edit=true')

    if request.method == 'POST':
        ruling = 'yes' in request.POST
        person_judged = Person.objects.get(pk=request.POST['person_pk'])
        judgement = Judgement(judge=person, judged=person_judged, ruling = ruling)
        try:
            judgement.save()
        except IntegrityError:
            pass
        if ruling:
            group_service.index(judgement)

    suggested_person = person_service.get_random_person(person)
    return render_to_response('people.html', {'user': user, 'suggested_person': suggested_person}, context_instance=RequestContext(request))

def groups(request):
    if not request.user.is_active:
        return redirect('/accounts/login')
    user = request.user
    person = user.person
    if person is None:
        return redirect('/accounts/profile/?edit=true')

    groups = person.group_set.all()
    return render_to_response('groups.html', {'user': user, 'groups': groups})

def create_fake_people(request):
    fake_service.create_fake_people()

templates/account.html
{% block account %}

{% if user and user.is_active %}
<a href="/accounts/logout/">Logout {{user.username}}</a>
{% else %}
<a href="/accounts/login/">Login</a> or <a href="/accounts/register/">Register</a>
{% endif %}

{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta http-equiv="x-ua-compatible" content="ie=edge" />
<meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1" />
<title>Group Tinder</title>

<!--[if (gt IE 8) | (IEMobile)]><!-->
<link rel="stylesheet" href="./stylesheets/application.css" />
<!--<![endif]-->

<!--[if (lt IE 9) & (!IEMobile)]>
<link rel="stylesheet" href="./stylesheets/application-ie.css" />
<![endif]-->

</head>
<body>
    <div><h1>{% block title %}{{ section.title }}{% endblock %}</h1></div>
    <div>{% include "main_nav.html" %}</div>
    <div>{% include "account.html" %}</div>
    <div>
        {% block content %}
        {% endblock %}
    </div>
</body>
</html>

templates/groups.html
{% extends "base.html" %}

{% block title %}Groups{% endblock %}

{% block content %}
<div>
    {% if groups %}
        <p>These are the groups you have matched with:</p>
        {% for group in groups %}
            <div>
                {% for person in group.people.all %}
                    {{person.user.username}},
                {% endfor %}
            </div>
        {% endfor %}
    {% else %}
        <p>You haven't matched with any groups. Flip through more people to find a match: <a href="/people/">People</a></p>
    {% endif %}
</div>
{% endblock %}

templates/home.html
{% extends "base.html" %}

{% block title %}Group Tinder{% endblock %}

{% block content %}
<p>What is this? A way to find people you'd be willing to meet and hang with as a group. Why does it look so janky? Because it's a prototype. I purposefully spent 0 time worrying about how it looks. I want to see if it's a good idea and can help you meet and connect with new people.</p>

<p>How's it work? Flip through a stack of suggested people. Click yes or no if you'd meet this person in a group setting. When 3 or more people click yes for eachother, a group is made. Then you can chat with this group and figure out if you all want to meet up or not.</p>

<p><a href="/accounts/register">Register</a> to get started.</p>
{% endblock %}

templates/main_nav.html
{% block main_nav %}

<a href="/home/">Home</a>
<a href="/accounts/profile/">View Profile</a>
<a href="/people/">People</a>
<a href="/groups/">Groups</a>

{% endblock %}

templates/people.html
{% extends "base.html" %}

{% block title %}People{% endblock %}

{% block content %}
<div>
    <div>Name: {{suggested_person.user.username}}</div>
    <div>Age: {{suggested_person.age}}</div>
    <div>Gender: {{suggested_person.get_gender_display}}</div>
    <div>Stereotype: {{suggested_person.get_stereotype_display}}</div>
    <form action="/people/" method="post" />
        {% csrf_token %}
        <div>Would hang with?</div>
        <input type="hidden" value="{{suggested_person.pk}}" name="person_pk" />
        <input type="submit" value="Yes" name="yes" />
        <input type="submit" value="No" name="no" />
    </form>
</div>
{% endblock %}

templates/profile.html
{% extends "base.html" %}

{% block title %}Profile{% endblock %}

{% block content %}
{% if form %}
<form action="/accounts/profile/" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Submit" />
</form>
{% else %}
<div>
    <div>Name: {{user.username}}</div>
    <div>Age: {{person.age}}</div>
    <div>Gender: {{person.get_gender_display}}</div>
    <div>Stereotype: {{person.get_stereotype_display}}</div>
</div>
<a href="/accounts/profile?edit=true">Edit Profile</a>
{% endif %}
{% endblock %}